# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    
    - name: SSH Remote Commands
  # You may pin to the exact commit or the version.
  # uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6
      uses: appleboy/ssh-action@v0.1.10
      with:
    # ssh host
        host: ${{secrets.AWS_EC2_INSTANCE_IP_ADDRESS}}
        key:  ${{secrets.AWS_EC2_INSTANCE_SSH_KEY}}
        username: ${{secrets.AWS_EC2_INSTANCE_USERNAME}}
        script: |
          cd /var/www/html
          sudo rm -rf race-bridge/
          sudo rm -rf bridge/
          sudo git clone https://github.com/RACE-Community/bridge.git
          sudo mv /var/www/html/bridge /var/www/html/race-bridge
          sudo systemctl restart nginx
